binop_separator = "Back"
brace_style = "PreferSameLine"
combine_control_expr = false
condense_wildcard_suffixes = true
empty_item_single_line = false
format_code_in_doc_comments = true
fn_params_layout = "Vertical"
group_imports = "StdExternalCrate"
hard_tabs = true
imports_layout = "Vertical"
imports_granularity = "One"
match_arm_blocks = false
reorder_impl_items = true
reorder_imports = true
spaces_around_ranges = true
struct_lit_single_line = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true